package com.mrcrayfish.furniture.init;

import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.item.ItemBlock;

import com.mrcrayfish.furniture.blocks.*;
import com.mrcrayfish.furniture.items.*;

public class FurnitureBlocks
{
    /* Initial Furniture */
    public static final Block COFFEE_TABLE_OAK, COFFEE_TABLE_STONE;
    public static final Block TABLE_OAK, TABLE_STONE;
    public static final Block CHAIR_OAK, CHAIR_STONE;
    public static final Block FREEZER, FRIDGE;
    public static final Block CABINET_OAK, BEDSIDE_CABINET_OAK;
    public static final Block COUCH, COUCH_JEB, COUCH_FRAMED, COUCH_FRAMED_JEB;
    public static final BlockBlinds BLINDS_OAK, BLINDS_OAK_CLOSED;
    public static final Block CURTAINS, CURTAINS_CLOSED;
    public static final Block OVEN, RANGE_HOOD, RANGE_HOOD_POWERED;

    /* Garden Update */
    public static final Block HEDGE_OAK, HEDGE_SPRUCE, HEDGE_BIRCH, HEDGE_JUNGLE, HEDGE_ACACIA, HEDGE_DARK_OAK;
    public static final Block BIRD_BATH, STONE_PATH, WHITE_FENCE, TAP, MAIL_BOX_OAK;

    /* Electronic Update */
    public static final Block TV, RETRO_TV, COMPUTER, MODERN_COMPUTER, PRINTER, ELECTRIC_FENCE, DOOR_BELL, STEREO;
    public static final Block FIRE_ALARM_OFF, FIRE_ALARM_ON;
    public static final Block CEILING_LIGHT_OFF, CEILING_LIGHT_ON;
    public static final Block LAMP_ON, LAMP_OFF;

    /* Bathroom Update */
    public static final Block TOILET, BASIN, BATH_1, BATH_2;
    public static final Block SHOWER_BOTTOM, SHOWER_TOP, SHOWER_HEAD_OFF, SHOWER_HEAD_ON;
    public static final Block WALL_CABINET;
    public static final Block BIN;
    public static final Block MODERN_BIN;
    public static final Block WHEELIE_BIN;

    /* Kitchen Update */
    public static final Block TOASTER, MICROWAVE, BLENDER, WASHING_MACHINE, DISHWASHER;
    public static final Block COUNTER, COUNTER_SINK, KITCHEN_CABINET;
    public static final Block CUP, BOTTLE, PLATE, COOKIE_JAR, BAR_STOOL, CHOPPING_BOARD;

    /* Christmas Update */
    public static final Block PRESENT, TREE_BOTTOM, TREE_TOP;
    public static final Block MANTEL_PIECE, GRAND_CHAIR_TOP, GRAND_CHAIR_BOTTOM, CANDLE, CHIMNEY, WREATH, FAIRY_LIGHT, FIRE_PIT_OFF, FIRE_PIT_ON;

    /* Outdoor Update */
    public static final Block TRAMPOLINE, CRATE, BENCH, TABLE_OUTDOOR, GRILL, DIVING_BOARD_BASE, DIVING_BOARD_PLANK, DOOR_MAT, COOLER;
    public static final Block COFFEE_TABLE_SPRUCE, COFFEE_TABLE_BIRCH, COFFEE_TABLE_JUNGLE, COFFEE_TABLE_ACACIA, COFFEE_TABLE_DARK_OAK;
    public static final Block CHAIR_SPRUCE, CHAIR_BIRCH, CHAIR_JUNGLE, CHAIR_ACACIA, CHAIR_DARK_OAK;
    public static final Block TABLE_SPRUCE, TABLE_BIRCH, TABLE_JUNGLE, TABLE_ACACIA, TABLE_DARK_OAK;
    public static final Block CABINET_SPRUCE, CABINET_BIRCH, CABINET_JUNGLE, CABINET_ACACIA, CABINET_DARK_OAK;
    public static final Block BEDSIDE_CABINET_SPRUCE, BEDSIDE_CABINET_BIRCH, BEDSIDE_CABINET_JUNGLE, BEDSIDE_CABINET_ACACIA, BEDSIDE_CABINET_DARK_OAK;

    /* More Stone Furniture Update */
    public static final Block COFFEE_TABLE_GRANITE, COFFEE_TABLE_DIORITE, COFFEE_TABLE_ANDESITE;
    public static final Block TABLE_GRANITE, TABLE_DIORITE, TABLE_ANDESITE;
    public static final Block CHAIR_GRANITE, CHAIR_DIORITE, CHAIR_ANDESITE;

    /* The Modern Update */
    public static final Block BEDSIDE_CABINET_STONE, BEDSIDE_CABINET_GRANITE, BEDSIDE_CABINET_DIORITE, BEDSIDE_CABINET_ANDESITE;
    public static final Block MODERN_WINDOW, MODERN_SLIDING_DOOR, MODERN_SLIDING_DOOR_OAK, MODERN_SLIDING_DOOR_SPRUCE, MODERN_SLIDING_DOOR_BIRCH, MODERN_SLIDING_DOOR_JUNGLE, MODERN_SLIDING_DOOR_ACACIA, MODERN_SLIDING_DOOR_DARK_OAK, MODERN_TV, MODERN_COUCH, MODERN_TABLE, MODERN_CHAIR, MODERN_BED_TOP, MODERN_BED_BOTTOM, MODERN_COFFEE_TABLE, MODERN_STAIRS, MODERN_TABLE_OUTDOOR;
    public static final Block LIGHT_SWITCH_OFF, LIGHT_SWITCH_ON, MODERN_LIGHT_OFF, MODERN_LIGHT_ON, OLD_LIGHT_OFF, OLD_LIGHT_ON;
    public static final Block CEILING_FAN;
    public static final Block DESK_OAK, DESK_SPRUCE, DESK_BIRCH, DESK_JUNGLE, DESK_ACACIA, DESK_DARK_OAK, DESK_STONE, DESK_GRANITE, DESK_DIORITE, DESK_ANDESITE;
    public static final Block DESK_CABINET_OAK, DESK_CABINET_SPRUCE, DESK_CABINET_BIRCH, DESK_CABINET_JUNGLE, DESK_CABINET_ACACIA, DESK_CABINET_DARK_OAK, DESK_CABINET_STONE, DESK_CABINET_GRANITE, DESK_CABINET_DIORITE, DESK_CABINET_ANDESITE;
    public static final Block CABINET_STONE, CABINET_GRANITE, CABINET_DIORITE, CABINET_ANDESITE;
    public static final Block DIGITAL_CLOCK;
    public static final Block COUNTER_DRAWER;
    public static final Block MAIL_BOX_SPRUCE, MAIL_BOX_BIRCH, MAIL_BOX_JUNGLE, MAIL_BOX_ACACIA, MAIL_BOX_DARK_OAK;
    public static final Block DOOR_BELL_SPRUCE, DOOR_BELL_BIRCH, DOOR_BELL_JUNGLE, DOOR_BELL_ACACIA, DOOR_BELL_DARK_OAK;
    public static final Block PHOTO_FRAME;
    public static final Block DISPLAY_FRAME;
    public static final Block CRATE_SPRUCE, CRATE_BIRCH, CRATE_JUNGLE, CRATE_ACACIA, CRATE_DARK_OAK;
    public static final Block TV_STAND;
    public static final BlockBlinds BLINDS_SPRUCE, BLINDS_SPRUCE_CLOSED;
    public static final BlockBlinds BLINDS_BIRCH, BLINDS_BIRCH_CLOSED;
    public static final BlockBlinds BLINDS_JUNGLE, BLINDS_JUNGLE_CLOSED;
    public static final BlockBlinds BLINDS_ACACIA, BLINDS_ACACIA_CLOSED;
    public static final BlockBlinds BLINDS_DARK_OAK, BLINDS_DARK_OAK_CLOSED;

    /* The Outdoor Update V2 */
    public static final Block OAK_FENCE_UPGRADED, SPRUCE_FENCE_UPGRADED, BIRCH_FENCE_UPGRADED, JUNGLE_FENCE_UPGRADED, ACACIA_FENCE_UPGRADED, DARK_OAK_FENCE_UPGRADED, NETHER_BRICK_FENCE_UPGRADED;
    public static final Block OAK_GATE_UPGRADED, SPRUCE_GATE_UPGRADED, BIRCH_GATE_UPGRADED, JUNGLE_GATE_UPGRADED, ACACIA_GATE_UPGRADED, DARK_OAK_GATE_UPGRADED;
    public static final Block WHITE_GATE;
    public static final Block OAK_PARK_BENCH, SPRUCE_PARK_BENCH, BIRCH_PARK_BENCH, JUNGLE_PARK_BENCH, ACACIA_PARK_BENCH, DARK_OAK_PARK_BENCH;
    public static final Block INFLATABLE_CASTLE, CASTLE_NETTING;

    /* Random Furniture */
    public static final Block MIRROR;
    public static final Block SERVICE_BELL;
    public static final Block BOWL;
    public static final Block BOWL_FOOD;
    public static final Block BOWL_CAT_FOOD;
    public static final Block BOWL_WATER;
    public static final Block PET_BED;
    public static final Block PET_COUCH;
    public static final Block PIXEL_BOX;
    public static final Block WATER_TANK;
    public static final Block BIRD_HOUSE;
    public static final Block SMALL_LIGHT_OFF;
    public static final Block SMALL_LIGHT_ON;
    public static final Block BOWL_FOOD_SECRET;
    public static final Block CAMP_CHAIR;
    public static final Block CAMP_CHAIR_SPRUCE;
    public static final Block CAMP_CHAIR_BIRCH;
    public static final Block CAMP_CHAIR_JUNGLE;
    public static final Block CAMP_CHAIR_ACACIA;
    public static final Block CAMP_CHAIR_DARK_OAK;
    public static final Block BIRD_BATH_WATER;
    public static final Block MODERN_OAK_STAIR;
    public static final Block FOOD_DISPENSER;
    public static final Block FOOD_DISPENSER_CAT;
    public static final Block LITTER_BOX;
    public static final Block CAT_TREE;
    public static final Block RADIATOR;
    public static final Block FIGURINE_MRCRAYFISH;

    /* Nostalgia Update */
    public static final Block WOODEN_CHAIR_OLD;
    public static final Block STONE_CHAIR_OLD;
    public static final Block WOODEN_TABLE_OLD;
    public static final Block STONE_TABLE_OLD;
    public static final Block CABINET_OLD;
    public static final Block CABINET_CLASSIC;
    public static final Block BEDSIDE_CABINET_OLD;
    public static final Block WOODEN_COFFEE_TABLE_OLD;
    public static final Block STONE_COFFEE_TABLE_OLD;
    public static final Block FREEZER_OLD;
    public static final Block FRIDGE_OLD;
    public static final Block COUCH_OLD;
    public static final Block BLINDS_OLD;
    public static final Block BLINDS_OLD_CLOSED;
    public static final Block CURTAIN_OLD;
    public static final Block CURTAIN_CLOSED_OLD;
    public static final Block CARPET_CLASSIC_WHITE;
    public static final Block CARPET_CLASSIC_GREEN;
    public static final Block CARPET_CLASSIC_BROWN;
    public static final Block CARPET_CLASSIC_RED;
    public static final Block CARPET_CLASSIC_BLACK;
    public static final Block OVEN_OLD;
    public static final Block RANGE_HOOD_OLD;
    public static final Block HEDGE_OAK_OLD;
    public static final Block HEDGE_SPRUCE_OLD;
    public static final Block HEDGE_BIRCH_OLD;
    public static final Block HEDGE_JUNGLE_OLD;
    public static final Block HEDGE_ACACIA_OLD;
    public static final Block HEDGE_DARK_OAK_OLD;
    public static final Block BIRD_BATH_OLD;
    public static final Block STONE_PATH_OLD;
    public static final Block WHITE_FENCE_OLD;
    public static final Block TAP_OLD;
    public static final Block MAIL_BOX_OLD;
    public static final Block TV_OLD;
    public static final Block COMPUTER_OLD;
    public static final Block PRINTER_OLD;
    public static final Block STEREO_OLD;
    public static final Block CEILING_LIGHT_ON_OLD;
    public static final Block CEILING_LIGHT_OFF_OLD;
    public static final Block DOOR_BELL_OLD;
    public static final Block TOILET_OLD;
    public static final Block BASIN_OLD;
    public static final Block WALL_CABINET_OLD;
    public static final Block BATH_OLD_1;
    public static final Block BATH_OLD_2;
    public static final Block SHOWER_BOTTOM_OLD;
    public static final Block SHOWER_TOP_OLD;
    public static final Block BIN_OLD;
    public static final Block PRESENT_RED_OLD;
    public static final Block PRESENT_GREEN_OLD;
    public static final Block TOASTER_OLD;
    public static final Block MICROWAVE_OLD;
    public static final Block WASHING_MACHINE_OLD;
    public static final Block COOKIE_JAR_OLD;
    public static final Block BLENDER_OLD;
    public static final Block PLATE_OLD;
    public static final Block COUNTER_OLD;
    public static final Block COUNTER_KITCHEN_SINK_OLD;
    public static final Block DISHWASHER_OLD;
    public static final Block KITCHEN_CABINET_OLD;
    public static final Block CHOPPING_BOARD_OLD;
    public static final Block BAR_STOOL_OLD;

    static
    {
        COFFEE_TABLE_OAK = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_oak");
        COFFEE_TABLE_SPRUCE = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_spruce");
        COFFEE_TABLE_BIRCH = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_birch");
        COFFEE_TABLE_JUNGLE = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_jungle");
        COFFEE_TABLE_ACACIA = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_acacia");
        COFFEE_TABLE_DARK_OAK = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_dark_oak");
        COFFEE_TABLE_STONE = new BlockCoffeeTable(Material.ROCK, SoundType.STONE, "coffee_table_stone");
        TABLE_OAK = new BlockTable(Material.WOOD, SoundType.WOOD, "table_oak");
        TABLE_SPRUCE = new BlockTable(Material.WOOD, SoundType.WOOD, "table_spruce");
        TABLE_BIRCH = new BlockTable(Material.WOOD, SoundType.WOOD, "table_birch");
        TABLE_JUNGLE = new BlockTable(Material.WOOD, SoundType.WOOD, "table_jungle");
        TABLE_ACACIA = new BlockTable(Material.WOOD, SoundType.WOOD, "table_acacia");
        TABLE_DARK_OAK = new BlockTable(Material.WOOD, SoundType.WOOD, "table_dark_oak");
        TABLE_STONE = new BlockTable(Material.ROCK, SoundType.STONE, "table_stone");
        CHAIR_OAK = new BlockChair(Material.WOOD, SoundType.WOOD, "chair_oak");
        CHAIR_SPRUCE = new BlockChair(Material.WOOD, SoundType.WOOD, "chair_spruce");
        CHAIR_BIRCH = new BlockChair(Material.WOOD, SoundType.WOOD, "chair_birch");
        CHAIR_JUNGLE = new BlockChair(Material.WOOD, SoundType.WOOD, "chair_jungle");
        CHAIR_ACACIA = new BlockChair(Material.WOOD, SoundType.WOOD, "chair_acacia");
        CHAIR_DARK_OAK = new BlockChair(Material.WOOD, SoundType.WOOD, "chair_dark_oak");
        CHAIR_STONE = new BlockChair(Material.ROCK, SoundType.STONE, "chair_stone");
        FREEZER = new BlockFreezer(Material.IRON, "freezer");
        FRIDGE = new BlockFridge(Material.IRON, "fridge");
        CABINET_OAK = new BlockCabinet(Material.WOOD, "cabinet_oak");
        CABINET_SPRUCE = new BlockCabinet(Material.WOOD, "cabinet_spruce");
        CABINET_BIRCH = new BlockCabinet(Material.WOOD, "cabinet_birch");
        CABINET_JUNGLE = new BlockCabinet(Material.WOOD, "cabinet_jungle");
        CABINET_ACACIA = new BlockCabinet(Material.WOOD, "cabinet_acacia");
        CABINET_DARK_OAK = new BlockCabinet(Material.WOOD, "cabinet_dark_oak");
        COUCH = new BlockCouchNormal("couch");
        COUCH_JEB = new BlockCouchJeb("couch_jeb");
        COUCH_FRAMED = new BlockCouchNormal("couch_framed");
        COUCH_FRAMED_JEB = new BlockCouchJeb("couch_framed_jeb");
        LAMP_ON = new BlockLampOn(Material.GLASS, "lamp_on");
        LAMP_OFF = new BlockLamp(Material.GLASS, false, "lamp_off");
        BLINDS_OAK = new BlockBlinds(Material.WOOD, true, "blinds_open");
        BLINDS_OAK_CLOSED = new BlockBlinds(Material.WOOD, false, "blinds_closed");
        BLINDS_SPRUCE = new BlockBlinds(Material.WOOD, true, "blinds_spruce_open");
        BLINDS_SPRUCE_CLOSED = new BlockBlinds(Material.WOOD, false, "blinds_spruce_closed");
        BLINDS_BIRCH = new BlockBlinds(Material.WOOD, true, "blinds_birch_open");
        BLINDS_BIRCH_CLOSED = new BlockBlinds(Material.WOOD, false, "blinds_birch_closed");
        BLINDS_JUNGLE = new BlockBlinds(Material.WOOD, true, "blinds_jungle_open");
        BLINDS_JUNGLE_CLOSED = new BlockBlinds(Material.WOOD, false, "blinds_jungle_closed");
        BLINDS_ACACIA = new BlockBlinds(Material.WOOD, true, "blinds_acacia_open");
        BLINDS_ACACIA_CLOSED = new BlockBlinds(Material.WOOD, false, "blinds_acacia_closed");
        BLINDS_DARK_OAK = new BlockBlinds(Material.WOOD, true, "blinds_dark_oak_open");
        BLINDS_DARK_OAK_CLOSED = new BlockBlinds(Material.WOOD, false, "blinds_dark_oak_closed");
        CURTAINS = new BlockCurtainsOpen(Material.CLOTH, "curtains_open");
        CURTAINS_CLOSED = new BlockCurtainsClosed(Material.CLOTH, "curtains_closed");
        BEDSIDE_CABINET_OAK = new BlockBedsideCabinet(Material.WOOD, "bedside_cabinet_oak");
        BEDSIDE_CABINET_SPRUCE = new BlockBedsideCabinet(Material.WOOD, "bedside_cabinet_spruce");
        BEDSIDE_CABINET_BIRCH = new BlockBedsideCabinet(Material.WOOD, "bedside_cabinet_birch");
        BEDSIDE_CABINET_JUNGLE = new BlockBedsideCabinet(Material.WOOD, "bedside_cabinet_jungle");
        BEDSIDE_CABINET_ACACIA = new BlockBedsideCabinet(Material.WOOD, "bedside_cabinet_acacia");
        BEDSIDE_CABINET_DARK_OAK = new BlockBedsideCabinet(Material.WOOD, "bedside_cabinet_dark_oak");
        OVEN = new BlockOven(Material.ROCK, "oven");
        RANGE_HOOD = new BlockRangeHood(Material.ROCK, false, "range_hood");
        RANGE_HOOD_POWERED = new BlockRangeHood(Material.ROCK, true, "range_hood_powered");
        HEDGE_OAK = new BlockHedge("hedge_oak");
        HEDGE_SPRUCE = new BlockHedge("hedge_spruce");
        HEDGE_BIRCH = new BlockHedge("hedge_birch");
        HEDGE_JUNGLE = new BlockHedge("hedge_jungle");
        HEDGE_ACACIA = new BlockHedge("hedge_acacia");
        HEDGE_DARK_OAK = new BlockHedge("hedge_dark_oak");
        BIRD_BATH = new BlockBirdBath(Material.ROCK, "bird_bath");
        STONE_PATH = new BlockStonePath(Material.ROCK, "stone_path");
        WHITE_FENCE = new BlockWhiteFence(Material.WOOD, "white_fence");
        TAP = new BlockTap(Material.ROCK, "tap");
        MAIL_BOX_OAK = new BlockMailBox(Material.WOOD, "mail_box");
        MAIL_BOX_SPRUCE = new BlockMailBox(Material.WOOD, "mail_box_spruce");
        MAIL_BOX_BIRCH = new BlockMailBox(Material.WOOD, "mail_box_birch");
        MAIL_BOX_JUNGLE = new BlockMailBox(Material.WOOD, "mail_box_jungle");
        MAIL_BOX_ACACIA = new BlockMailBox(Material.WOOD, "mail_box_acacia");
        MAIL_BOX_DARK_OAK = new BlockMailBox(Material.WOOD, "mail_box_dark_oak");
        TV = new BlockTV(Material.WOOD, "tv");
        RETRO_TV = new BlockRetroTV(Material.WOOD, "retro_tv");
        COMPUTER = new BlockComputer(Material.IRON, "computer");
        MODERN_COMPUTER = new BlockModernComputer(Material.IRON, "modern_computer");
        PRINTER = new BlockPrinter(Material.IRON, "printer");
        ELECTRIC_FENCE = new BlockElectricFence(Material.ROCK, "electric_fence");
        DOOR_BELL = new BlockDoorBell(Material.WOOD, "door_bell");
        DOOR_BELL_SPRUCE = new BlockDoorBell(Material.WOOD, "door_bell_spruce");
        DOOR_BELL_BIRCH = new BlockDoorBell(Material.WOOD, "door_bell_birch");
        DOOR_BELL_JUNGLE = new BlockDoorBell(Material.WOOD, "door_bell_jungle");
        DOOR_BELL_ACACIA = new BlockDoorBell(Material.WOOD, "door_bell_acacia");
        DOOR_BELL_DARK_OAK = new BlockDoorBell(Material.WOOD, "door_bell_dark_oak");
        FIRE_ALARM_ON = new BlockFireAlarm(Material.ROCK, true, "fire_alarm_on");
        FIRE_ALARM_OFF = new BlockFireAlarm(Material.ROCK, false, "fire_alarm_off");
        CEILING_LIGHT_ON = new BlockCeilingLight(Material.GLASS, true, "ceiling_light_on");
        CEILING_LIGHT_OFF = new BlockCeilingLight(Material.GLASS, false, "ceiling_light_off");
        STEREO = new BlockStereo(Material.WOOD, "stereo");
        TOILET = new BlockToilet(Material.ROCK, "toilet");
        BASIN = new BlockBasin(Material.ROCK, "basin");
        WALL_CABINET = new BlockWallCabinet(Material.ROCK, "wall_cabinet");
        BATH_1 = new BlockBath(Material.ROCK, false, "bath_bottom");
        BATH_2 = new BlockBath(Material.ROCK, true, "bath_top");
        SHOWER_BOTTOM = new BlockShower(Material.ROCK, false, "shower_bottom");
        SHOWER_TOP = new BlockShower(Material.ROCK, true, "shower_top");
        SHOWER_HEAD_OFF = new BlockShowerHeadOff(Material.ROCK, "shower_head_off");
        SHOWER_HEAD_ON = new BlockShowerHeadOn(Material.ROCK, "shower_head_on");
        BIN = new BlockBin(Material.ROCK, "bin");
        MODERN_BIN = new BlockBin(Material.ROCK, "modern_bin");
        WHEELIE_BIN = new BlockWheelieBin(Material.CLAY, "wheelie_bin");
        TREE_TOP = new BlockTree(Material.WOOD, true, "tree_top");
        TREE_BOTTOM = new BlockTree(Material.WOOD, false, "tree_bottom");
        PRESENT = new BlockPresent(Material.CLOTH, "present");
        TOASTER = new BlockToaster(Material.ROCK, "toaster");
        MICROWAVE = new BlockMicrowave(Material.WOOD, "microwave");
        WASHING_MACHINE = new BlockWashingMachine(Material.ROCK, "washing_machine");
        COOKIE_JAR = new BlockCookieJar(Material.GLASS, "cookie_jar");
        BLENDER = new BlockBlender(Material.GLASS, "blender");
        CUP = new BlockCup(Material.GLASS, "cup");
        BOTTLE = new BlockBottle(Material.GLASS, "bottle");
        PLATE = new BlockPlate(Material.GLASS, "plate");
        COUNTER = new BlockCounter(Material.ROCK, "counter");
        COUNTER_SINK = new BlockCounterSink(Material.ROCK, "counter_sink");
        COUNTER_DRAWER = new BlockCounterDrawer(Material.ROCK, "counter_drawer");
        DISHWASHER = new BlockDishwasher(Material.ROCK, "dishwasher");
        KITCHEN_CABINET = new BlockCabinetKitchen(Material.WOOD, "cabinet_kitchen");
        CHOPPING_BOARD = new BlockChoppingBoard(Material.WOOD, "chopping_board");
        BAR_STOOL = new BlockBarStool(Material.WOOD, "bar_stool");
        MIRROR = new BlockMirror(Material.GLASS, "mirror");
        MANTEL_PIECE = new BlockMantelPiece(Material.ROCK, "mantel_piece");
        GRAND_CHAIR_TOP = new BlockGrandChair(Material.WOOD, true, "grand_chair_top");
        GRAND_CHAIR_BOTTOM = new BlockGrandChair(Material.WOOD, false, "grand_chair_bottom");
        CANDLE = new BlockCandle(Material.ROCK, "candle");
        CHIMNEY = new BlockChimney(Material.ROCK, "chimney");
        WREATH = new BlockWreath(Material.LEAVES, "wreath");
        FAIRY_LIGHT = new BlockFairyLight(Material.GLASS, "fairy_light");
        FIRE_PIT_OFF = new BlockFirePitOff(Material.WOOD, "fire_pit_off");
        FIRE_PIT_ON = new BlockFirePitOn(Material.WOOD, "fire_pit_on");
        TRAMPOLINE = new BlockTrampoline(Material.ROCK, "trampoline");
        CRATE = new BlockCrate(Material.WOOD, "crate");
        BENCH = new BlockBench(Material.WOOD, "bench");
        TABLE_OUTDOOR = new BlockOutdoorTable(Material.WOOD, SoundType.WOOD, "table_outdoor");
        GRILL = new BlockGrill(Material.ANVIL, "grill");
        DIVING_BOARD_BASE = new BlockDivingboard(Material.ROCK, false, "divingboard_base");
        DIVING_BOARD_PLANK = new BlockDivingboard(Material.ROCK, true, "divingboard_plank");
        DOOR_MAT = new BlockDoorMat(Material.CLOTH, "door_mat");
        COOLER = new BlockEsky(Material.CLAY, "esky");
        COFFEE_TABLE_GRANITE = new BlockCoffeeTable(Material.ROCK, SoundType.STONE, "coffee_table_granite");
        COFFEE_TABLE_DIORITE = new BlockCoffeeTable(Material.ROCK, SoundType.STONE, "coffee_table_diorite");
        COFFEE_TABLE_ANDESITE = new BlockCoffeeTable(Material.ROCK, SoundType.STONE, "coffee_table_andesite");
        TABLE_GRANITE = new BlockTable(Material.ROCK, SoundType.STONE, "table_granite");
        TABLE_DIORITE = new BlockTable(Material.ROCK, SoundType.STONE, "table_diorite");
        TABLE_ANDESITE = new BlockTable(Material.ROCK, SoundType.STONE, "table_andesite");
        CHAIR_GRANITE = new BlockChair(Material.ROCK, SoundType.STONE, "chair_granite");
        CHAIR_DIORITE = new BlockChair(Material.ROCK, SoundType.STONE, "chair_diorite");
        CHAIR_ANDESITE = new BlockChair(Material.ROCK, SoundType.STONE, "chair_andesite");
        BEDSIDE_CABINET_STONE = new BlockBedsideCabinet(Material.ROCK, "bedside_cabinet_stone");
        BEDSIDE_CABINET_GRANITE = new BlockBedsideCabinet(Material.ROCK, "bedside_cabinet_granite");
        BEDSIDE_CABINET_DIORITE = new BlockBedsideCabinet(Material.ROCK, "bedside_cabinet_diorite");
        BEDSIDE_CABINET_ANDESITE = new BlockBedsideCabinet(Material.ROCK, "bedside_cabinet_andesite");
        MODERN_WINDOW = new BlockModernWindow("modern_window");
        MODERN_SLIDING_DOOR = new BlockModernSlidingDoor("modern_sliding_door");
        MODERN_SLIDING_DOOR_OAK = new BlockModernSlidingDoor("modern_sliding_door_oak");
        MODERN_SLIDING_DOOR_SPRUCE = new BlockModernSlidingDoor("modern_sliding_door_spruce");
        MODERN_SLIDING_DOOR_BIRCH = new BlockModernSlidingDoor("modern_sliding_door_birch");
        MODERN_SLIDING_DOOR_JUNGLE = new BlockModernSlidingDoor("modern_sliding_door_jungle");
        MODERN_SLIDING_DOOR_ACACIA = new BlockModernSlidingDoor("modern_sliding_door_acacia");
        MODERN_SLIDING_DOOR_DARK_OAK = new BlockModernSlidingDoor("modern_sliding_door_dark_oak");
        LIGHT_SWITCH_OFF = new BlockLightSwitch("light_switch_off");
        LIGHT_SWITCH_ON = new BlockLightSwitch("light_switch_on");
        CEILING_FAN = new BlockCeilingFan("ceiling_fan");
        DESK_OAK = new BlockDesk(Material.WOOD, "desk_oak");
        DESK_SPRUCE = new BlockDesk(Material.WOOD, "desk_spruce");
        DESK_BIRCH = new BlockDesk(Material.WOOD, "desk_birch");
        DESK_JUNGLE = new BlockDesk(Material.WOOD, "desk_jungle");
        DESK_ACACIA = new BlockDesk(Material.WOOD, "desk_acacia");
        DESK_DARK_OAK = new BlockDesk(Material.WOOD, "desk_dark_oak");
        DESK_STONE = new BlockDesk(Material.ROCK, "desk_stone");
        DESK_GRANITE = new BlockDesk(Material.ROCK, "desk_granite");
        DESK_DIORITE = new BlockDesk(Material.ROCK, "desk_diorite");
        DESK_ANDESITE = new BlockDesk(Material.ROCK, "desk_andesite");
        DESK_CABINET_OAK = new BlockDeskCabinet(Material.WOOD, "desk_cabinet_oak");
        DESK_CABINET_SPRUCE = new BlockDeskCabinet(Material.WOOD, "desk_cabinet_spruce");
        DESK_CABINET_BIRCH = new BlockDeskCabinet(Material.WOOD, "desk_cabinet_birch");
        DESK_CABINET_JUNGLE = new BlockDeskCabinet(Material.WOOD, "desk_cabinet_jungle");
        DESK_CABINET_ACACIA = new BlockDeskCabinet(Material.WOOD, "desk_cabinet_acacia");
        DESK_CABINET_DARK_OAK = new BlockDeskCabinet(Material.WOOD, "desk_cabinet_dark_oak");
        DESK_CABINET_STONE = new BlockDeskCabinet(Material.ROCK, "desk_cabinet_stone");
        DESK_CABINET_GRANITE = new BlockDeskCabinet(Material.ROCK, "desk_cabinet_granite");
        DESK_CABINET_DIORITE = new BlockDeskCabinet(Material.ROCK, "desk_cabinet_diorite");
        DESK_CABINET_ANDESITE = new BlockDeskCabinet(Material.ROCK, "desk_cabinet_andesite");
        CABINET_STONE = new BlockCabinet(Material.ROCK, "cabinet_stone");
        CABINET_GRANITE = new BlockCabinet(Material.ROCK, "cabinet_granite");
        CABINET_DIORITE = new BlockCabinet(Material.ROCK, "cabinet_diorite");
        CABINET_ANDESITE = new BlockCabinet(Material.ROCK, "cabinet_andesite");
        DIGITAL_CLOCK = new BlockDigitalClock("digital_clock");
        MODERN_TV = new BlockModernTV("modern_tv");
        PHOTO_FRAME = new BlockPhotoFrame("photo_frame");
        DISPLAY_FRAME = new BlockDisplayFrame("display_frame");
        MODERN_COUCH = new BlockModernCouch("modern_couch");
        MODERN_TABLE = new BlockModernTable("modern_table");
        MODERN_CHAIR = new BlockChair(Material.WOOD, SoundType.WOOD, "modern_chair");
        CRATE_SPRUCE = new BlockCrate(Material.WOOD, "crate_spruce");
        CRATE_BIRCH = new BlockCrate(Material.WOOD, "crate_birch");
        CRATE_JUNGLE = new BlockCrate(Material.WOOD, "crate_jungle");
        CRATE_ACACIA = new BlockCrate(Material.WOOD, "crate_acacia");
        CRATE_DARK_OAK = new BlockCrate(Material.WOOD, "crate_dark_oak");
        MODERN_BED_TOP = new BlockModernBed("modern_bed_top");
        MODERN_BED_BOTTOM = new BlockModernBed("modern_bed_bottom");
        TV_STAND = new BlockTVStand("tv_stand");
        MODERN_COFFEE_TABLE = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "modern_coffee_table");
        MODERN_STAIRS = new BlockModernStair("modern_stair");
        MODERN_TABLE_OUTDOOR = new BlockModernTable("modern_table_outdoor");
        MODERN_LIGHT_OFF = new BlockModernLight("modern_light_off", false);
        MODERN_LIGHT_ON = new BlockModernLight("modern_light_on", true);
        OLD_LIGHT_OFF = new BlockOldLight("old_light_off", false);
        OLD_LIGHT_ON = new BlockOldLight("old_light_on", true);
        OAK_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_oak");
        SPRUCE_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_spruce");
        BIRCH_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_birch");
        JUNGLE_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_jungle");
        ACACIA_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_acacia");
        DARK_OAK_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_dark_oak");
        NETHER_BRICK_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_nether_brick");
        OAK_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_oak");
        SPRUCE_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_spruce");
        BIRCH_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_birch");
        JUNGLE_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_jungle");
        ACACIA_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_acacia");
        DARK_OAK_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_dark_oak");
        WHITE_GATE = new BlockWhiteGate("white_gate");
        OAK_PARK_BENCH = new BlockParkBench("park_bench_oak");
        SPRUCE_PARK_BENCH = new BlockParkBench("park_bench_spruce");
        BIRCH_PARK_BENCH = new BlockParkBench("park_bench_birch");
        JUNGLE_PARK_BENCH = new BlockParkBench("park_bench_jungle");
        ACACIA_PARK_BENCH = new BlockParkBench("park_bench_acacia");
        DARK_OAK_PARK_BENCH = new BlockParkBench("park_bench_dark_oak");
        INFLATABLE_CASTLE = new BlockInflatableCastle("inflatable_castle");
        CASTLE_NETTING = new BlockCastleNetting("castle_netting");
        SERVICE_BELL = new BlockServiceBell(Material.IRON, "service_bell");
        BOWL = new BlockBowl(Material.IRON, "bowl");
        BOWL_FOOD = new BlockBowl(Material.IRON, "bowl_food");
        BOWL_CAT_FOOD = new BlockBowl(Material.IRON, "bowl_cat_food");
        BOWL_WATER = new BlockBowl(Material.IRON, "bowl_water");
        FOOD_DISPENSER = new BlockFoodDispenser(Material.IRON, "food_dispenser");
        FOOD_DISPENSER_CAT = new BlockFoodDispenserCat(Material.IRON, "food_dispenser_cat");
        PET_BED = new BlockPetBed(Material.WOOD, "pet_bed");
        PET_COUCH = new BlockPetCouch(Material.WOOD, "pet_couch");
        PIXEL_BOX = new BlockPixelBox(Material.IRON, "pixel_box");
        WATER_TANK = new BlockWaterTank(Material.WOOD, "water_tank");
        BIRD_HOUSE = new BlockBirdHouse(Material.WOOD, "bird_house");
        SMALL_LIGHT_OFF = new BlockSmallLight("small_light_off", false);
        SMALL_LIGHT_ON = new BlockSmallLight("small_light_on", true);
        BOWL_FOOD_SECRET = new BlockBowlFoodSecret(Material.IRON, "bowl_food_secret");
        CAMP_CHAIR = new BlockCampChair(Material.WOOD, "camp_chair");
        CAMP_CHAIR_SPRUCE = new BlockCampChair(Material.WOOD, "camp_chair_spruce");
        CAMP_CHAIR_BIRCH = new BlockCampChair(Material.WOOD, "camp_chair_birch");
        CAMP_CHAIR_JUNGLE = new BlockCampChair(Material.WOOD, "camp_chair_jungle");
        CAMP_CHAIR_ACACIA = new BlockCampChair(Material.WOOD, "camp_chair_acacia");
        CAMP_CHAIR_DARK_OAK = new BlockCampChair(Material.WOOD, "camp_chair_dark_oak");
        BIRD_BATH_WATER = new BlockBirdBathWater(Material.ROCK, "bird_bath_water");
        MODERN_OAK_STAIR = new BlockModernOakStair("modern_oak_stair");
        LITTER_BOX = new BlockLitterBox(Material.WOOD, "litter_box");
        CAT_TREE = new BlockCatTree(Material.WOOD, "cat_tree");
        RADIATOR = new BlockRadiator(Material.IRON, "radiator");
        FIGURINE_MRCRAYFISH = new BlockFigurineMrcrayfish(Material.ROCK, "figurine_mrcrayfish");
        WOODEN_CHAIR_OLD = new BlockOldChair(Material.WOOD, SoundType.WOOD, "chair_oak_old");
        STONE_CHAIR_OLD = new BlockOldChair(Material.ROCK, SoundType.STONE, "chair_stone_old");
        WOODEN_TABLE_OLD = new BlockOldTable(Material.WOOD, SoundType.WOOD, "table_oak_old");
        STONE_TABLE_OLD = new BlockOldTable(Material.ROCK, SoundType.STONE, "table_stone_old");
        CABINET_OLD = new BlockOldCabinet(Material.WOOD, "cabinet_old");
        CABINET_CLASSIC = new BlockOldClassicCabinet(Material.WOOD, "classic_cabinet");
        BEDSIDE_CABINET_OLD = new BlockOldBedsideCabinet(Material.WOOD, "bedside_cabinet_old");
        WOODEN_COFFEE_TABLE_OLD = new BlockOldCoffeeTable(Material.WOOD, SoundType.WOOD, "wooden_coffee_table_old");
        STONE_COFFEE_TABLE_OLD = new BlockOldCoffeeTable(Material.ROCK, SoundType.STONE, "stone_coffee_table_old");
        FREEZER_OLD = new BlockOldFreezer(Material.IRON, "freezer_old");
        FRIDGE_OLD = new BlockOldFridge(Material.IRON, "fridge_old");
        COUCH_OLD = new BlockOldCouch("couch_old");
        BLINDS_OLD = new BlockOldBlinds(Material.WOOD, true, "blinds_open_old");
        BLINDS_OLD_CLOSED = new BlockOldBlinds(Material.WOOD, false, "blinds_closed_old");
        CURTAIN_OLD = new BlockOldCurtainOpen(Material.CLOTH, "curtain_open_old");
        CURTAIN_CLOSED_OLD = new BlockOldCurtainClosed(Material.CLOTH, "curtain_closed_old");
        CARPET_CLASSIC_WHITE = new BlockOldClassicCarpet(Material.CLOTH, "classic_carpet_white");
        CARPET_CLASSIC_GREEN = new BlockOldClassicCarpet(Material.CLOTH, "classic_carpet_green");
        CARPET_CLASSIC_BROWN = new BlockOldClassicCarpet(Material.CLOTH, "classic_carpet_brown");
        CARPET_CLASSIC_RED = new BlockOldClassicCarpet(Material.CLOTH, "classic_carpet_red");
        CARPET_CLASSIC_BLACK = new BlockOldClassicCarpet(Material.CLOTH, "classic_carpet_black");
        OVEN_OLD = new BlockOldOven(Material.ROCK, "oven_old");
        RANGE_HOOD_OLD = new BlockOldRangeHood(Material.ROCK, "range_hood_old");
        HEDGE_OAK_OLD = new BlockOldHedge("hedge_oak_old");
        HEDGE_SPRUCE_OLD = new BlockOldHedge("hedge_spruce_old");
        HEDGE_BIRCH_OLD = new BlockOldHedge("hedge_birch_old");
        HEDGE_JUNGLE_OLD = new BlockOldHedge("hedge_jungle_old");
        HEDGE_ACACIA_OLD = new BlockOldHedge("hedge_acacia_old");
        HEDGE_DARK_OAK_OLD = new BlockOldHedge("hedge_dark_oak_old");
        BIRD_BATH_OLD = new BlockOldBirdBath(Material.ROCK, "bird_bath_old");
        STONE_PATH_OLD = new BlockOldStonePath(Material.ROCK, "stone_path_old");
        WHITE_FENCE_OLD = new BlockOldWhiteFence(Material.WOOD, "white_fence_old");
        TAP_OLD = new BlockOldTap(Material.ROCK, "tap_old");
        MAIL_BOX_OLD = new BlockOldMailBox(Material.WOOD, "mail_box_old");
        TV_OLD = new BlockOldTv(Material.WOOD, "tv_old");
        COMPUTER_OLD = new BlockOldComputer(Material.IRON, "computer_old");
        PRINTER_OLD = new BlockOldPrinter(Material.IRON, "printer_old");
        STEREO_OLD = new BlockOldStereo(Material.WOOD, "stereo_old");
        CEILING_LIGHT_ON_OLD = new BlockOldCeilingLight(Material.GLASS, true, "ceiling_light_on_old");
        CEILING_LIGHT_OFF_OLD = new BlockOldCeilingLight(Material.GLASS, false, "ceiling_light_off_old");
        DOOR_BELL_OLD = new BlockOldDoorBell(Material.WOOD, "door_bell_old");
        TOILET_OLD = new BlockOldToilet(Material.ROCK, "toilet_old");
        BASIN_OLD = new BlockOldBasin(Material.ROCK, "basin_old");
        WALL_CABINET_OLD = new BlockOldWallCabinet(Material.ROCK, "wall_cabinet_old");
        BATH_OLD_1 = new BlockOldBath(Material.ROCK, false, "bath_bottom_old");
        BATH_OLD_2 = new BlockOldBath(Material.ROCK, true, "bath_top_old");
        SHOWER_BOTTOM_OLD = new BlockOldShower(Material.ROCK, false, "shower_bottom_old");
        SHOWER_TOP_OLD = new BlockOldShower(Material.ROCK, true, "shower_top_old");
        BIN_OLD = new BlockOldBin(Material.ROCK, "bin_old");
        PRESENT_RED_OLD = new BlockOldPresent(Material.CLOTH, "present_red_old");
        PRESENT_GREEN_OLD = new BlockOldPresent(Material.CLOTH, "present_green_old");
        TOASTER_OLD = new BlockOldToaster(Material.ROCK, "toaster_old");
        MICROWAVE_OLD = new BlockOldMicrowave(Material.ROCK, "microwave_old");
        WASHING_MACHINE_OLD = new BlockOldWashingMachine(Material.ROCK, "washing_machine_old");
        COOKIE_JAR_OLD = new BlockOldCookieJar(Material.GLASS, "cookie_jar_old");
        BLENDER_OLD = new BlockOldBlender(Material.GLASS, "blender_old");
        PLATE_OLD = new BlockOldPlate(Material.GLASS, "plate_old");
        COUNTER_OLD = new BlockOldCounter(Material.WOOD, "counter_old");
        COUNTER_KITCHEN_SINK_OLD = new BlockOldCounterSink(Material.ROCK, "counter_sink_old");
        DISHWASHER_OLD = new BlockOldDishwasher(Material.ROCK, "dishwasher_old");
        KITCHEN_CABINET_OLD = new BlockOldCabinetKitchen(Material.WOOD, "cabinet_kitchen_old");
        CHOPPING_BOARD_OLD = new BlockOldChoppingBoard(Material.WOOD, "chopping_board_old");
        BAR_STOOL_OLD = new BlockOldBarStool(Material.ROCK, "bar_stool_old");
    }

    public static void register()
    {
        registerBlock(COFFEE_TABLE_OAK);
        registerBlock(COFFEE_TABLE_SPRUCE);
        registerBlock(COFFEE_TABLE_BIRCH);
        registerBlock(COFFEE_TABLE_JUNGLE);
        registerBlock(COFFEE_TABLE_ACACIA);
        registerBlock(COFFEE_TABLE_DARK_OAK);
        registerBlock(COFFEE_TABLE_STONE);
        registerBlock(COFFEE_TABLE_GRANITE);
        registerBlock(COFFEE_TABLE_DIORITE);
        registerBlock(COFFEE_TABLE_ANDESITE);
        registerBlock(TABLE_OAK);
        registerBlock(TABLE_SPRUCE);
        registerBlock(TABLE_BIRCH);
        registerBlock(TABLE_JUNGLE);
        registerBlock(TABLE_ACACIA);
        registerBlock(TABLE_DARK_OAK);
        registerBlock(TABLE_STONE);
        registerBlock(TABLE_GRANITE);
        registerBlock(TABLE_DIORITE);
        registerBlock(TABLE_ANDESITE);
        registerBlock(CHAIR_OAK);
        registerBlock(CHAIR_SPRUCE);
        registerBlock(CHAIR_BIRCH);
        registerBlock(CHAIR_JUNGLE);
        registerBlock(CHAIR_ACACIA);
        registerBlock(CHAIR_DARK_OAK);
        registerBlock(CHAIR_STONE);
        registerBlock(CHAIR_GRANITE);
        registerBlock(CHAIR_DIORITE);
        registerBlock(CHAIR_ANDESITE);
        registerBlock(FREEZER);
        registerBlock(FRIDGE, null);
        registerBlock(CABINET_OAK);
        registerBlock(CABINET_SPRUCE);
        registerBlock(CABINET_BIRCH);
        registerBlock(CABINET_JUNGLE);
        registerBlock(CABINET_ACACIA);
        registerBlock(CABINET_DARK_OAK);
        registerBlock(CABINET_STONE);
        registerBlock(CABINET_GRANITE);
        registerBlock(CABINET_DIORITE);
        registerBlock(CABINET_ANDESITE);
        registerBlock(COUCH, new ItemBlockColored(COUCH));
        registerBlock(COUCH_JEB);
        registerBlock(COUCH_FRAMED, new ItemBlockColored(COUCH_FRAMED));
        registerBlock(COUCH_FRAMED_JEB);
        registerBlock(LAMP_ON, null);
        registerBlock(LAMP_OFF, new ItemBlockColored(LAMP_OFF));
        registerBlock(BLINDS_OAK);
        registerBlock(BLINDS_OAK_CLOSED, null);
        registerBlock(BLINDS_SPRUCE);
        registerBlock(BLINDS_SPRUCE_CLOSED, null);
        registerBlock(BLINDS_BIRCH);
        registerBlock(BLINDS_BIRCH_CLOSED, null);
        registerBlock(BLINDS_JUNGLE);
        registerBlock(BLINDS_JUNGLE_CLOSED, null);
        registerBlock(BLINDS_ACACIA);
        registerBlock(BLINDS_ACACIA_CLOSED, null);
        registerBlock(BLINDS_DARK_OAK);
        registerBlock(BLINDS_DARK_OAK_CLOSED, null);
        registerBlock(CURTAINS, new ItemColoredFurniture(CURTAINS));
        registerBlock(CURTAINS_CLOSED, null);
        registerBlock(BEDSIDE_CABINET_OAK);
        registerBlock(BEDSIDE_CABINET_SPRUCE);
        registerBlock(BEDSIDE_CABINET_BIRCH);
        registerBlock(BEDSIDE_CABINET_JUNGLE);
        registerBlock(BEDSIDE_CABINET_ACACIA);
        registerBlock(BEDSIDE_CABINET_DARK_OAK);
        registerBlock(BEDSIDE_CABINET_STONE);
        registerBlock(BEDSIDE_CABINET_GRANITE);
        registerBlock(BEDSIDE_CABINET_DIORITE);
        registerBlock(BEDSIDE_CABINET_ANDESITE);
        registerBlock(OVEN);
        registerBlock(RANGE_HOOD);
        registerBlock(RANGE_HOOD_POWERED, null);
        registerBlock(HEDGE_OAK, new ItemHedge(HEDGE_OAK));
        registerBlock(HEDGE_SPRUCE, new ItemHedge(HEDGE_SPRUCE));
        registerBlock(HEDGE_BIRCH, new ItemHedge(HEDGE_BIRCH));
        registerBlock(HEDGE_JUNGLE, new ItemHedge(HEDGE_JUNGLE));
        registerBlock(HEDGE_ACACIA, new ItemHedge(HEDGE_ACACIA));
        registerBlock(HEDGE_DARK_OAK, new ItemHedge(HEDGE_DARK_OAK));
        registerBlock(BIRD_BATH);
        registerBlock(STONE_PATH);
        registerBlock(WHITE_FENCE);
        registerBlock(WHITE_GATE, new ItemUpgradedGate(WHITE_GATE));
        registerBlock(TAP);
        registerBlock(MAIL_BOX_OAK);
        registerBlock(MAIL_BOX_SPRUCE);
        registerBlock(MAIL_BOX_BIRCH);
        registerBlock(MAIL_BOX_JUNGLE);
        registerBlock(MAIL_BOX_ACACIA);
        registerBlock(MAIL_BOX_DARK_OAK);
        registerBlock(TV);
        registerBlock(RETRO_TV);
        registerBlock(COMPUTER);
        registerBlock(MODERN_COMPUTER);
        registerBlock(PRINTER);
        registerBlock(ELECTRIC_FENCE);
        registerBlock(DOOR_BELL);
        registerBlock(DOOR_BELL_SPRUCE);
        registerBlock(DOOR_BELL_BIRCH);
        registerBlock(DOOR_BELL_JUNGLE);
        registerBlock(DOOR_BELL_ACACIA);
        registerBlock(DOOR_BELL_DARK_OAK);
        registerBlock(FIRE_ALARM_OFF);
        registerBlock(FIRE_ALARM_ON);
        registerBlock(CEILING_LIGHT_OFF);
        registerBlock(CEILING_LIGHT_ON, null);
        registerBlock(STEREO);
        registerBlock(TOILET);
        registerBlock(BASIN);
        registerBlock(WALL_CABINET);
        registerBlock(BATH_1, new ItemBath(BATH_1));
        registerBlock(BATH_2, null);
        registerBlock(SHOWER_BOTTOM);
        registerBlock(SHOWER_TOP, null);
        registerBlock(SHOWER_HEAD_OFF);
        registerBlock(SHOWER_HEAD_ON, null);
        registerBlock(BIN);
        registerBlock(MODERN_BIN);
        registerBlock(WHEELIE_BIN);
        registerBlock(PRESENT, new ItemPresent(PRESENT));
        registerBlock(TREE_TOP, null);
        registerBlock(TREE_BOTTOM, new ItemWreath(TREE_BOTTOM));
        registerBlock(TOASTER);
        registerBlock(MICROWAVE);
        registerBlock(WASHING_MACHINE);
        registerBlock(COOKIE_JAR);
        registerBlock(BLENDER);
        registerBlock(CUP, null);
        registerBlock(BOTTLE, null);
        registerBlock(PLATE);
        registerBlock(COUNTER, new ItemBlockColored(COUNTER));
        registerBlock(COUNTER_SINK, new ItemBlockColored(COUNTER_SINK));
        registerBlock(COUNTER_DRAWER, new ItemBlockColored(COUNTER_DRAWER));
        registerBlock(DISHWASHER);
        registerBlock(KITCHEN_CABINET, new ItemBlockColored(KITCHEN_CABINET));
        registerBlock(CHOPPING_BOARD);
        registerBlock(BAR_STOOL, new ItemBlockColored(BAR_STOOL));
        registerBlock(MIRROR);
        registerBlock(MANTEL_PIECE);
        registerBlock(GRAND_CHAIR_TOP, null);
        registerBlock(GRAND_CHAIR_BOTTOM);
        registerBlock(CANDLE);
        registerBlock(CHIMNEY);
        registerBlock(WREATH, new ItemWreath(WREATH));
        registerBlock(FAIRY_LIGHT);
        registerBlock(FIRE_PIT_OFF, null);
        registerBlock(FIRE_PIT_ON);
        registerBlock(TRAMPOLINE);
        registerBlock(CRATE, new ItemCrate(CRATE));
        registerBlock(CRATE_SPRUCE, new ItemCrate(CRATE_SPRUCE));
        registerBlock(CRATE_BIRCH, new ItemCrate(CRATE_BIRCH));
        registerBlock(CRATE_JUNGLE, new ItemCrate(CRATE_JUNGLE));
        registerBlock(CRATE_ACACIA, new ItemCrate(CRATE_ACACIA));
        registerBlock(CRATE_DARK_OAK, new ItemCrate(CRATE_DARK_OAK));
        registerBlock(BENCH);
        registerBlock(TABLE_OUTDOOR);
        registerBlock(GRILL);
        registerBlock(DIVING_BOARD_BASE, new ItemBath(DIVING_BOARD_BASE));
        registerBlock(DIVING_BOARD_PLANK, null);
        registerBlock(DOOR_MAT, new ItemBlockColored(DOOR_MAT));
        registerBlock(COOLER, new ItemBlockColored(COOLER));
        registerBlock(MODERN_WINDOW);
        registerBlock(MODERN_SLIDING_DOOR, new ItemModernSlidingDoor(MODERN_SLIDING_DOOR));
        registerBlock(MODERN_SLIDING_DOOR_OAK, new ItemModernSlidingDoor(MODERN_SLIDING_DOOR_OAK));
        registerBlock(MODERN_SLIDING_DOOR_SPRUCE, new ItemModernSlidingDoor(MODERN_SLIDING_DOOR_SPRUCE));
        registerBlock(MODERN_SLIDING_DOOR_BIRCH, new ItemModernSlidingDoor(MODERN_SLIDING_DOOR_BIRCH));
        registerBlock(MODERN_SLIDING_DOOR_JUNGLE, new ItemModernSlidingDoor(MODERN_SLIDING_DOOR_JUNGLE));
        registerBlock(MODERN_SLIDING_DOOR_ACACIA, new ItemModernSlidingDoor(MODERN_SLIDING_DOOR_ACACIA));
        registerBlock(MODERN_SLIDING_DOOR_DARK_OAK, new ItemModernSlidingDoor(MODERN_SLIDING_DOOR_DARK_OAK));
        registerBlock(LIGHT_SWITCH_OFF, new ItemLightSwitch(LIGHT_SWITCH_OFF));
        registerBlock(LIGHT_SWITCH_ON, null);
        registerBlock(CEILING_FAN);
        registerBlock(DESK_OAK);
        registerBlock(DESK_SPRUCE);
        registerBlock(DESK_BIRCH);
        registerBlock(DESK_JUNGLE);
        registerBlock(DESK_ACACIA);
        registerBlock(DESK_DARK_OAK);
        registerBlock(DESK_STONE);
        registerBlock(DESK_GRANITE);
        registerBlock(DESK_DIORITE);
        registerBlock(DESK_ANDESITE);
        registerBlock(DESK_CABINET_OAK);
        registerBlock(DESK_CABINET_SPRUCE);
        registerBlock(DESK_CABINET_BIRCH);
        registerBlock(DESK_CABINET_JUNGLE);
        registerBlock(DESK_CABINET_ACACIA);
        registerBlock(DESK_CABINET_DARK_OAK);
        registerBlock(DESK_CABINET_STONE);
        registerBlock(DESK_CABINET_GRANITE);
        registerBlock(DESK_CABINET_DIORITE);
        registerBlock(DESK_CABINET_ANDESITE);
        registerBlock(DIGITAL_CLOCK, new ItemColored(DIGITAL_CLOCK));
        registerBlock(MODERN_TV);
        registerBlock(PHOTO_FRAME, new ItemColoredFurniture(PHOTO_FRAME));
        registerBlock(DISPLAY_FRAME);
        registerBlock(MODERN_COUCH, new ItemColoredFurniture(MODERN_COUCH));
        registerBlock(MODERN_TABLE);
        registerBlock(MODERN_CHAIR);
        registerBlock(MODERN_COFFEE_TABLE);
        registerBlock(MODERN_TABLE_OUTDOOR);
        registerBlock(MODERN_STAIRS);
        registerBlock(MODERN_BED_TOP, null);
        registerBlock(MODERN_BED_BOTTOM, new ItemModernBed());
        registerBlock(TV_STAND);
        registerBlock(MODERN_LIGHT_OFF);
        registerBlock(MODERN_LIGHT_ON, null);
        registerBlock(OLD_LIGHT_OFF);
        registerBlock(OLD_LIGHT_ON, null);
        registerBlock(OAK_FENCE_UPGRADED);
        registerBlock(SPRUCE_FENCE_UPGRADED);
        registerBlock(BIRCH_FENCE_UPGRADED);
        registerBlock(JUNGLE_FENCE_UPGRADED);
        registerBlock(ACACIA_FENCE_UPGRADED);
        registerBlock(DARK_OAK_FENCE_UPGRADED);
        registerBlock(NETHER_BRICK_FENCE_UPGRADED);
        registerBlock(OAK_GATE_UPGRADED, new ItemUpgradedGate(OAK_GATE_UPGRADED));
        registerBlock(SPRUCE_GATE_UPGRADED, new ItemUpgradedGate(SPRUCE_GATE_UPGRADED));
        registerBlock(BIRCH_GATE_UPGRADED, new ItemUpgradedGate(BIRCH_GATE_UPGRADED));
        registerBlock(JUNGLE_GATE_UPGRADED, new ItemUpgradedGate(JUNGLE_GATE_UPGRADED));
        registerBlock(ACACIA_GATE_UPGRADED, new ItemUpgradedGate(ACACIA_GATE_UPGRADED));
        registerBlock(DARK_OAK_GATE_UPGRADED, new ItemUpgradedGate(DARK_OAK_GATE_UPGRADED));
        registerBlock(OAK_PARK_BENCH);
        registerBlock(SPRUCE_PARK_BENCH);
        registerBlock(BIRCH_PARK_BENCH);
        registerBlock(JUNGLE_PARK_BENCH);
        registerBlock(ACACIA_PARK_BENCH);
        registerBlock(DARK_OAK_PARK_BENCH);
        registerBlock(INFLATABLE_CASTLE, new ItemColored(INFLATABLE_CASTLE));
        registerBlock(CASTLE_NETTING);
        registerBlock(SERVICE_BELL);
        registerBlock(FOOD_DISPENSER);
        registerBlock(FOOD_DISPENSER_CAT);
        registerBlock(BOWL);
        registerBlock(BOWL_FOOD);
        registerBlock(BOWL_CAT_FOOD);
        registerBlock(BOWL_WATER);
        registerBlock(PET_BED);
        registerBlock(PET_COUCH);
        registerBlock(PIXEL_BOX);
        registerBlock(WATER_TANK);
        registerBlock(BIRD_HOUSE);
        registerBlock(BIRD_BATH_WATER);
        registerBlock(SMALL_LIGHT_OFF);
        registerBlock(SMALL_LIGHT_ON, null);
        registerBlock(MODERN_OAK_STAIR);
        registerBlock(BOWL_FOOD_SECRET);
        registerBlock(CAMP_CHAIR);
        registerBlock(CAMP_CHAIR_SPRUCE);
        registerBlock(CAMP_CHAIR_BIRCH);
        registerBlock(CAMP_CHAIR_JUNGLE);
        registerBlock(CAMP_CHAIR_ACACIA);
        registerBlock(CAMP_CHAIR_DARK_OAK);
        registerBlock(LITTER_BOX);
        registerBlock(CAT_TREE);
        registerBlock(RADIATOR);
        registerBlock(FIGURINE_MRCRAYFISH);
        registerBlock(WOODEN_CHAIR_OLD);
        registerBlock(STONE_CHAIR_OLD);
        registerBlock(WOODEN_TABLE_OLD);
        registerBlock(STONE_TABLE_OLD);
        registerBlock(CABINET_OLD);
        registerBlock(CABINET_CLASSIC);
        registerBlock(BEDSIDE_CABINET_OLD);
        registerBlock(WOODEN_COFFEE_TABLE_OLD);
        registerBlock(STONE_COFFEE_TABLE_OLD);
        registerBlock(FREEZER_OLD);
        registerBlock(FRIDGE_OLD, null);
        registerBlock(COUCH_OLD);
        registerBlock(BLINDS_OLD);
        registerBlock(BLINDS_OLD_CLOSED, null);
        registerBlock(CURTAIN_OLD);
        registerBlock(CURTAIN_CLOSED_OLD, null);
        registerBlock(CARPET_CLASSIC_WHITE);
        registerBlock(CARPET_CLASSIC_GREEN);
        registerBlock(CARPET_CLASSIC_BROWN);
        registerBlock(CARPET_CLASSIC_RED);
        registerBlock(CARPET_CLASSIC_BLACK);
        registerBlock(OVEN_OLD);
        registerBlock(RANGE_HOOD_OLD);
        registerBlock(HEDGE_OAK_OLD, new ItemHedge(HEDGE_OAK_OLD));
        registerBlock(HEDGE_SPRUCE_OLD, new ItemHedge(HEDGE_SPRUCE_OLD));
        registerBlock(HEDGE_BIRCH_OLD, new ItemHedge(HEDGE_BIRCH_OLD));
        registerBlock(HEDGE_JUNGLE_OLD, new ItemHedge(HEDGE_JUNGLE_OLD));
        registerBlock(HEDGE_ACACIA_OLD, new ItemHedge(HEDGE_ACACIA_OLD));
        registerBlock(HEDGE_DARK_OAK_OLD, new ItemHedge(HEDGE_DARK_OAK_OLD));
        registerBlock(BIRD_BATH_OLD);
        registerBlock(STONE_PATH_OLD);
        registerBlock(WHITE_FENCE_OLD);
        registerBlock(TAP_OLD);
        registerBlock(MAIL_BOX_OLD);
        registerBlock(TV_OLD);
        registerBlock(COMPUTER_OLD);
        registerBlock(PRINTER_OLD);
        registerBlock(STEREO_OLD);
        registerBlock(CEILING_LIGHT_OFF_OLD);
        registerBlock(CEILING_LIGHT_ON_OLD, null);
        registerBlock(DOOR_BELL_OLD);
        registerBlock(TOILET_OLD);
        registerBlock(BASIN_OLD);
        registerBlock(WALL_CABINET_OLD);
        registerBlock(BATH_OLD_1, new ItemBath(BATH_OLD_1));
        registerBlock(BATH_OLD_2, null);
        registerBlock(SHOWER_BOTTOM_OLD);
        registerBlock(SHOWER_TOP_OLD, null);
        registerBlock(BIN_OLD);
        registerBlock(PRESENT_RED_OLD);
        registerBlock(PRESENT_GREEN_OLD);
        registerBlock(TOASTER_OLD);
        registerBlock(MICROWAVE_OLD);
        registerBlock(WASHING_MACHINE_OLD);
        registerBlock(COOKIE_JAR_OLD);
        registerBlock(BLENDER_OLD);
        registerBlock(PLATE_OLD);
        registerBlock(COUNTER_OLD);
        registerBlock(COUNTER_KITCHEN_SINK_OLD);
        registerBlock(DISHWASHER_OLD);
        registerBlock(KITCHEN_CABINET_OLD);
        registerBlock(CHOPPING_BOARD_OLD);
        registerBlock(BAR_STOOL_OLD);
    }

    public static void registerBlock(Block block)
    {
        registerBlock(block, new ItemBlock(block));
    }

    public static void registerBlock(Block block, ItemBlock item)
    {
        if (block.getRegistryName() == null)
        {
            throw new IllegalArgumentException("A block being registered does not have a registry name and could not be successfully registered.");
        }

        RegistrationHandler.Blocks.add(block);

        if (item != null)
        {
            item.setRegistryName(block.getRegistryName());
            RegistrationHandler.Items.add(item);
        }
    }
}
